language: objective-c
osx_image: xcode10.1
script:
- swift build
- swift test
- pod setup
- pod lib lint --skip-import-validation --skip-tests --allow-warnings
before_deploy:
- swift build --static-swift-stdlib --configuration release
- export BINARY_PATH=`swift build --show-bin-path --configuration release`/TezosGen
- mv "$BINARY_PATH" .
- zip -r tezosgen-$TRAVIS_TAG.zip LICENSE TezosGen
after_deploy:
- pod trunk push --skip-import-validation --skip-tests --allow-warnings
deploy:
  provider: releases
  api_key:
    secure: mdkzl0b3xQ11QMgvK9ot4kRuMhc5GBZ/FxrOkNn7B8ssc/X/kxgcO01tY5K1pfqyKrf4RzjbxLq8jmztGZgfViBhepI0Ofx9vD7xjy0Vm+5sSueKLWKG0/53nTgZbcvv5aul7Cbz3Czjlm7g7U940OXWltz/lO2bhGBk22DWG4OWynqwivzs5V9uqWmyva9KpJLm+EXrc5AiV8IyAYafQ44gRmi9AExQm9YXXWxkT+S3nwcVpUv2Hk2aHDkFJx/iurWiOtuc5br1HnBfNhPkZNgPsoNEfPv2s9mHZE+ThMgsk1tHMZpU5ekz+QTwRBCbQOHIJ5L0VCJaCTu10Ajlu92ErxRJVq9IFVFO2VceJmdBmorUjwDIixYc4yENdALL9RUBhB4XMrvg8d3639F1SUzsOBFY4CCw372rINUGLnoBBh/6bs2NnsG2kjNYxKANHOxbBCGQNykSTK4jR6z8yuovfp5XLtRGzC49/ZKzuA3F8hBkp6wVXtwgtcjllhvmvBPXXJ7oip/7ztygQFhwb4Xn+rqLjyq4flMZLJlYZrxY8n51ssiQH3K4ZgVTxpofx2hEYD33TLjPpeg5OSf7Z2C0uNzIFyJ+PuuQG+J9SBShO+tJYcb/rzFxSGUHPxL1ymOf0okWrp11CROa4Do55tAQyrZlP7ZE32mcM3+ibsw=
  file: "tezosgen-$TRAVIS_TAG.zip"
  skip_cleanup: true
  on:
    repo: AckeeCZ/Tezos-iOS-Dev-Kit
    tags: true
